//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMLRetrainUsingSQL.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://ussouthcentral.services.azureml.net/workspaces/bfeea278c505495b866dc9a5df" +
            "a10018/services/36499f37fd3d4706a16d3d90fbaad996/jobs")]
        public string mlretrainermodelurl {
            get {
                return ((string)(this["mlretrainermodelurl"]));
            }
            set {
                this["mlretrainermodelurl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Y+1+7H7alQ2H9Yu7dVmiFc6fDO1vZbdbPIZZv434m2tAei9WgtlMHx186U7fdJyH/dwUdzy286EyjFkMc" +
            "BTAgg==")]
        public string mlretrainerkey {
            get {
                return ((string)(this["mlretrainerkey"]));
            }
            set {
                this["mlretrainerkey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("mlretrainerstoragejd")]
        public string mlstoragename {
            get {
                return ((string)(this["mlstoragename"]));
            }
            set {
                this["mlstoragename"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("N47GAKHoX5rjFqRox51McDthQ65nIKf77CYJ9vv/vG/6I9Bj2WwAp+LOuN+WIbJVgRE2gHUbDzdGsBofk" +
            "j2+WA==")]
        public string mlstoragekey {
            get {
                return ((string)(this["mlstoragekey"]));
            }
            set {
                this["mlstoragekey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("retrainerdata")]
        public string mlstoragecontainer {
            get {
                return ((string)(this["mlstoragecontainer"]));
            }
            set {
                this["mlstoragecontainer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string endpointname {
            get {
                return ((string)(this["endpointname"]));
            }
            set {
                this["endpointname"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string enpointurl {
            get {
                return ((string)(this["enpointurl"]));
            }
            set {
                this["enpointurl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string endpointkey {
            get {
                return ((string)(this["endpointkey"]));
            }
            set {
                this["endpointkey"] = value;
            }
        }
    }
}
